# get flutter container
container:
  image: cirrusci/flutter:latest

test_task:
  name: Tests
  pub_cache:
    folder: ~/.pub-cache
  script: flutter pub get
  test_script: flutter pub run test test/
