# Runs the all the tests written in the test folder.

# get flutter container
container:
  image: cirrusci/flutter:latest

task:
  name: Running Flutter Clean
  script: flutter clean

test_task:
  name: Running Local Tests
  pub_cache:
    folder: ~/.pub-cache

#  runs ```flutter pub get ``` before running the tests in the test/ folder
#  runs additional null assertions on the boundaries of migrated and un-migrated code.
  test_script: flutter test --pub --null-assertions

