  
name: Clean Flutter Builds and Format Code

on:
  push:
    branches:
      - '**'
      - '!production'
  
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  clean:
    runs-on: ubuntu-latest
    continue-on-error: true
    container:
      image: cirrusci/flutter:latest
    steps:
       - name: Checkout repository
         uses: actions/checkout@v2
       
       - name: Code Formatting
         run: flutter format . --line-length=200
        
       - name: Clean
         run: flutter clean
        
       - name: Commiting changes
         env:
           DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
           USERNAME: ${{ secrets.USERNAME }}
           EMAIL: ${{ secrets.EMAIL }}
         run: chmod +x scripts/commit.sh ; sh scripts/commit.sh
