name: Covergae Report
  uses: codecov/codecov-action@v2.1.0
  with:
    token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
    files: ./test/lcov.info
    flags: unittests, integrationtests
    name: test-coverage 
    verbose: true 
