name: Bob the Builder (Build & Deploy)

on:
  push:
    branches:
      - master
      
jobs:
  buid_and_deploy:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:latest
    steps:
       - name: Checkout repository
         uses: actions/checkout@v2
       
       - name: Running Local Tests
         run: flutter test --pub --null-assertions
       
       - name: Cleaning any previous builds
         run: flutter clean
         
       - name: Build Web App
         run:  flutter build web --pub --release --null-assertions
         
       - name: Upload Build Artifact
         uses: actions/upload-artifact@v2.2.4
         with:
          path: build/

    
    
  
    
