name: Bob the Builder (Build & Deploy)

on:
  push:
    branches:
      - production
      
jobs:
  buid_and_deploy:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:latest
    steps:
       - name: Checkout repository
         uses: actions/checkout@v2
       
       - name: Running Local Tests
         run: flutter test --pub --null-assertions
       
       - name: Cleaning any previous builds
         run: flutter clean
         
       - name: Build Web App
         run:  flutter build web --pub --release --null-assertions
         
       - run: git config --global user.email ${{ secrets.EMAIL }}
       - run: git config --global user.name ${{ secrets.USERNAME }}
       
       - run: git remote set-url origin https://${{ secrets.DEPLOY_TOKEN }}@github.com/Coders-Asylum/coders-asylum.github.io.git
       - run: git fetch --all
       - run: git pull origin
#        - run: cd build/web/
       - run: git add --all
       - run: git commit --all -m 'New Build'
       - name: Push Build to live branch
         run: git subtree push --prefix build/web origin live
    
    
  
    
