name: Bob the Builder (Build & Deploy)

on:
  push:
    branches:
      - production
      
jobs:
  buid_and_deploy:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:latest
    steps:
       - name: Checkout repository
         uses: actions/checkout@v2
       
       - name: Running Local Tests
         run: flutter test --pub --null-assertions
       
       - name: Cleaning any previous builds
         run: flutter clean
         
       - name: Build Web App
         run:  flutter build web --pub --release --null-assertions
         
       - name: Deploying Web App
         env:
           DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
           USERNAME: ${{ secrets.USERNAME }}
           EMAIL: ${{ secrets.EMAIL }}
         run: chmod +x ./.ci/deploy.sh ; sh ./.ci/deploy.sh
